//! SeaORM Entity. Generated by sea-orm-codegen 0.4.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "t_user_round")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub round_id: Option<i32>,
    pub user_address: String,
    pub dividends_earnings: Option<String>,
    pub buy_key_amount: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
